name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, macos, windows ]
    name: Build ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18.5.0
    - run: npm install
    - run: npm install -g pkg
    - run: pkg . --targets latest-${{ matrix.os }}-x64
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gltf-pipeline-${{ matrix.os }}
        path: gltf-pipeline*
